### ISSUE TITLE
extension for stable-diffusion-webui?

### ISSUE THREAD

**Issue by HyperUpscale** [tae-yeop/insetgan#1]
Hello,

Not sure how this github works... sorry about that in advance! 
I am just a user ...
Very popular is using https://github.com/AUTOMATIC1111/stable-diffusion-webui
I was just wondering if you can make body generation from a single portrait as extension to be added to the stable-diffusion-webui?

Thank you in advance!

**Comment by tae-yeop** [comment]
Hi, sorry for the late reply.

I'm not the original authors of this works. I was just trying to test out how this model works.

This model uses two StyleGAN to generate separate images of a face and a body. These generated images then go through an optimization process to make them look more natural, which means it refines the finer details. So this model don't generate the whole body in one-shot fashion. 

the interface of stable-diffusion-webui is basically gradio library which is not that hard to learn. But i don't have to much time to make this model to webui.

**Comment by HyperUpscale** [comment]
Thank you so much for the information!
